	/*  sccs id   @(#)  ex_vars.h  @(#)makeoptions	6.4 5/31/85  */
#define AUTOINDENT      0
#define AUTOPRINT       1
#define AUTOWRITE       2
#define BEAUTIFY        3
#define DIRECTORY       4
#define EDCOMPATIBLE    5
#define ERRORBELLS      6
#define EXINIT          7
#define FASTFG          8
#define FILESTACK       9
#define HARDTABS        10
#define IGNORECASE      11
#define LISP            12
#define LIST            13
#define MAGIC           14
#define MESG            15
#define MODELINE        16
#define NUMBER          17
#define OPEN            18
#define OPTIMIZE        19
#define PARAGRAPHS      20
#define PATH            21
#define PROMPT          22
#define READONLY        23
#define REDRAW          24
#define REMAP           25
#define REPORT          26
#define SCROLL          27
#define SECTIONS        28
#define SHELL           29
#define SHIFTWIDTH      30
#define SHOWMATCH       31
#define SLOWOPEN        32
#define TABSTOP         33
#define TAGLENGTH       34
#define TAGPREFIX       35
#define TAGS            36
#define TAGSTACK        37
#define TERM            38
#define TERSE           39
#define TIMEOUT         40
#define TTYTYPE         41
#define WARN            42
#define WINDOW          43
#define WRAPSCAN        44
#define WRAPMARGIN      45
#define WRITEANY        46

#define	NOPTS	47
