
#
#	Makefile for mklost+found
#
DESTDIR=

PROGRAM=	mklost+found
SRCS=		mklost+found.sh

all:
	@echo "\`mklost+found' is up to date"

install:
	install -c ${PROGRAM}.sh ${DESTDIR}/etc/${PROGRAM}

clean:

depend:
