#!/bin/sh

PATCHDIR=/usr/src/nntp/rrn
PATH=/usr/ucb:/usr/bin:/bin:/usr/local/bin:/usr/local
export PATH

for filename in Pnews.header addng.c artio.c common.h final.c head.c \
	init.c ng.c ngdata.c ngdata.h rcstuff.c respond.c util.c
do
patch -l $filename < $PATCHDIR/${filename}.rrnpatch
done


for filename in Makefile.SH newsetup.SH newsgroups.SH 
do
    patch -l -o ${filename}.rrn $filename < $PATCHDIR/${filename}.rrnpatch
done

if test -r Configure.orig ; then
echo "Configure.orig exists.  Save the real Configure script and then:"
echo '"mv Configure.rrn Configure"'
echo "Then run Configure and answer the questions."
else
mv Configure Configure.orig
mv Configure.rrn Configure
fi
